lang: ko
title: "Dan Dev Blog"
author:
  name: Dan
  email: yosub0901@gmail.com
description: "Dan dev Blog"
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: YosubLee
    
header_pages:

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
